### ISSUE TITLE
Marking Current date in ExpCalendarView issue

### ISSUE THREAD

**Issue by ghost** [SpongeBobSun/mCalendarView#15]
The Application seems to crash when Marking  current date in ExpCalendarView.

```
03-08 17:33:38.834 30477-30477/sun.bob.mcalendarviewtest E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           Process: sun.bob.mcalendarviewtest, PID: 30477
                                                                           java.lang.ClassCastException: sun.bob.mcalendarview.views.DefaultMarkView cannot be cast to sun.bob.mcalendarview.views.ExpandCellView
                                                                               at sun.bob.mcalendarview.adapters.CalendarExpAdapter.getView(CalendarExpAdapter.java:70)
                                                                               at android.widget.AbsListView.obtainView(AbsListView.java:2349)
                                                                               at android.widget.GridView.makeAndAddView(GridView.java:1433)
                                                                               at android.widget.GridView.makeRow(GridView.java:361)
                                                                               at android.widget.GridView.fillDown(GridView.java:302)
                                                                               at android.widget.GridView.fillFromTop(GridView.java:437)
                                                                               at android.widget.GridView.layoutChildren(GridView.java:1276)
                                                                               at android.widget.AbsListView.onLayout(AbsListView.java:2153)
                                                                               at android.view.View.layout(View.java:15686)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                               at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                                               at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1692)
                                                                               at android.widget.LinearLayout.onLayout(LinearLayout.java:1468)
                                                                               at android.view.View.layout(View.java:15686)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                               at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1627)
                                                                               at android.view.View.layout(View.java:15686)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                               at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                                               at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                                               at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                                               at android.view.View.layout(View.java:15686)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                               at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                               at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                               at android.view.View.layout(View.java:15686)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                               at android.support.v7.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:437)
                                                                               at android.view.View.layout(View.java:15686)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                               at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                               at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                               at android.view.View.layout(View.java:15686)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                               at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                                               at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                                               at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                                               at android.view.View.layout(View.java:15686)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                               at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                               at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                               at android.view.View.layout(View.java:15686)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                               at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2086)
                                                                               at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1843)
                                                                               at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
                                                                               at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5891)
                                                                               at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
                                                                               at android.view.Choreographer.doCallbacks(Choreographer.java:580)
                                                                               at android.view.Choreographer.doFrame(Choreographer.java:550)
                                                                               at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
                                                                               at android.os.Handler.handleCallback(Handler.java:739)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                               at android.os.Looper.loop(Looper.java:135)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5294)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at java.lang.reflect.Method.invoke(Method.java:372)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
```

Thanks

**Comment by SpongeBobSun** [comment]
Got it. Will fix it once I got time. Thanks for the feed back.

From Meizu MX4 Pro

-------- Original message --------
Sender: Rajakh notifications@github.com
Time: Tue 3/8 20:07
To: SpongeBobSun/mCalendarView mCalendarView@noreply.github.com
 Subject: [mCalendarView] Marking Current date in ExpCalendarView issue (#15)

> The Application seems to crash when Marking current date in ExpCalendarView. 03-08 17:33:38.834 30477-30477/sun.bob.mcalendarviewtest E/AndroidRuntime: FATAL EXCEPTION: main Process: sun.bob.mcalendarviewtest, PID: 30477 java.lang.ClassCastException: sun.bob.mcalendarview.views.DefaultMarkView cannot be cast to sun.bob.mcalendarview.views.ExpandCellView at sun.bob.mcalendarview.adapters.CalendarExpAdapter.getView(CalendarExpAdapter.java:70) at android.widget.AbsListView.obtainView(AbsListView.java:2349) at android.widget.GridView.makeAndAddView(GridView.java:1433) at android.widget.GridView.makeRow(GridView.java:361) at android.widget.GridView.fillDown(GridView.java:302) at android.widget.GridView.fillFromTop(GridView.java:437) at android.widget.GridView.layoutChildren(GridView.java:1276) at android.widget.AbsListView.onLayout(AbsListView.java:2153) at android.view.View.layout(View.java:15686) at android.view.ViewGroup.layout(ViewGroup.java:5039) at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703) at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1692) at android.widget.LinearLayout.onLayout(LinearLayout.java:1468) at android.view.View.layout(View.java:15686) at android.view.ViewGroup.layout(ViewGroup.java:5039) at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1627) at android.view.View.layout(View.java:15686) at android.view.ViewGroup.layout(ViewGroup.java:5039) at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703) at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557) at android.widget.LinearLayout.onLayout(LinearLayout.java:1466) at android.view.View.layout(View.java:15686) at android.view.ViewGroup.layout(ViewGroup.java:5039) at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579) at android.widget.FrameLayout.onLayout(FrameLayout.java:514) at android.view.View.layout(View.java:15686) at android.view.ViewGroup.layout(ViewGroup.java:5039) at android.support.v7.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:437) at android.view.View.layout(View.java:15686) at android.view.ViewGroup.layout(ViewGroup.java:5039) at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579) at android.widget.FrameLayout.onLayout(FrameLayout.java:514) at android.view.View.layout(View.java:15686) at android.view.ViewGroup.layout(ViewGroup.java:5039) at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703) at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557) at android.widget.LinearLayout.onLayout(LinearLayout.java:1466) at android.view.View.layout(View.java:15686) at android.view.ViewGroup.layout(ViewGroup.java:5039) at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579) at android.widget.FrameLayout.onLayout(FrameLayout.java:514) at android.view.View.layout(View.java:15686) at android.view.ViewGroup.layout(ViewGroup.java:5039) at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2086) at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1843) at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061) at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5891) at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767) at android.view.Choreographer.doCallbacks(Choreographer.java:580) at android.view.Choreographer.doFrame(Choreographer.java:550) at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753) at android.os.Handler.handleCallback(Handler.java:739) at android.os.Handler.dispatchMessage(Handler.java:95) at android.os.Looper.loop(Looper.java:135) at android.app.ActivityThread.main(ActivityThread.java:5294) at java.lang.reflect.Method.invoke(Native Method) at java.lang.reflect.Method.invoke(Method.java:372) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699) Thanks —Reply to this email directly or view it on GitHub.

**Comment by SpongeBobSun** [comment]
Fixed. Please pull the latest commit & verify.
Thanks.
