### ISSUE TITLE
Issue with the app

### ISSUE THREAD

**Issue by sebhanz** [SpongeBobSun/mCalendarView#39]
When I try to run it, the application closes and wont run

**Comment by SpongeBobSun** [comment]
More information please.

**Comment by sebhanz** [comment]
04-07 18:56:43.565 24511-24511/sun.bob.mcalendar E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: sun.bob.mcalendar, PID: 24511
                                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{sun.bob.mcalendar/sun.bob.mcalendar.activities.MainActivity}: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.calendar.CalendarProvider2 from ProcessRecord{cf9fb32 24511:sun.bob.mcalendar/u0a125} (pid=24511, uid=10125) requires android.permission.READ_CALENDAR or android.permission.WRITE_CALENDAR
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
                                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:154)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                                                                    Caused by: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.calendar.CalendarProvider2 from ProcessRecord{cf9fb32 24511:sun.bob.mcalendar/u0a125} (pid=24511, uid=10125) requires android.permission.READ_CALENDAR or android.permission.WRITE_CALENDAR
                                                                       at android.os.Parcel.readException(Parcel.java:1683)
                                                                       at android.os.Parcel.readException(Parcel.java:1636)
                                                                       at android.app.ActivityManagerProxy.getContentProvider(ActivityManagerNative.java:4169)
                                                                       at android.app.ActivityThread.acquireProvider(ActivityThread.java:5434)
                                                                       at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2267)
                                                                       at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1515)
                                                                       at android.content.ContentResolver.query(ContentResolver.java:514)
                                                                       at android.content.ContentResolver.query(ContentResolver.java:472)
                                                                       at sun.bob.mcalendar.content.CalendarResolver.getAllEvents(CalendarResolver.java:91)
                                                                       at sun.bob.mcalendar.activities.MainActivity.populateCalendar(MainActivity.java:100)
                                                                       at sun.bob.mcalendar.activities.MainActivity.onCreate(MainActivity.java:71)
                                                                       at android.app.Activity.performCreate(Activity.java:6662)
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707) 
                                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                       at android.os.Looper.loop(Looper.java:154) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by sebhanz** [comment]
The application wont open on the phone or emulator

**Comment by sebhanz** [comment]
Sorry this issue is happening with mCalendar not mCalendarView
